# Generated by Django 4.0.4 on 2022-06-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Points',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_add', models.IntegerField(default=0)),
                ('for_daily_login', models.IntegerField(default=1)),
                ('for_comments', models.IntegerField(default=0)),
                ('for_edit', models.IntegerField(default=0)),
                ('for_like', models.IntegerField(default=0)),
                ('for_visit', models.IntegerField(default=0)),
                ('for_bonus', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('description', models.TextField(blank=True, max_length=800, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('points', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.points')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
