# Generated by Django 4.0.4 on 2022-06-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='points',
            name='amt_adds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='points',
            name='amt_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='points',
            name='amt_edits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='points',
            name='amt_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='points',
            name='amt_visits',
            field=models.IntegerField(default=0),
        ),
    ]
