# Generated by Django 4.0.4 on 2022-05-31 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_to_do'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='to_do',
        ),
    ]
