# Generated by Django 4.0.4 on 2022-06-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_to_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='description',
            field=models.TextField(blank=True, max_length=800, null=True),
        ),
    ]
