# Generated by Django 4.0.4 on 2022-06-03 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_image_description_alter_image_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
