# Generated by Django 4.0.4 on 2022-06-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_remove_image_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilephoto',
            name='image',
            field=models.ImageField(default='user_profile_photo/default.jpg', upload_to='user_profile_photo/'),
        ),
    ]
