# Generated by Django 4.0.4 on 2022-06-02 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='finished',
            field=models.ManyToManyField(blank=True, related_name='puzzle_finished', to=settings.AUTH_USER_MODEL),
        ),
    ]
