# Generated by Django 4.0.4 on 2022-05-31 20:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('puzzle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='puzzle_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
