# Generated by Django 4.0.4 on 2022-05-19 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0002_puzzle_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
