# Generated by Django 4.0.4 on 2022-05-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0003_puzzle_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puzzle',
            name='note',
        ),
    ]
