# Generated by Django 4.0.4 on 2022-05-19 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle', '0004_remove_puzzle_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
